# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10f17987d8ee6b058fd96a5bff7f845d59b34c74a1b99c01fec2311310513be92bab341d4dcc7163e6b5c9901ee0d100888de710c18606466fc0d023c430740c

test:
  secret_key_base: 004ef7483b4a1e8c73dfd5226919314c75c09f003f8362a68a476c102aab0693fa183abed8c8e1bde4a18a219ae080562419fb94f8ef7755e462ff11d8ee5711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
